services:
  - type: web
    name: biogas-pb-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_USER
        fromDatabase:
          name: biogas-pb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: biogas-pb-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: biogas-pb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: biogas-pb-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: biogas-pb-db
          property: database

databases:
  - name: biogas-pb-db
    databaseName: biogas_pb
    user: biogas_user
    plan: free
